
jobs:
  - job: Ubuntu_1604_Hosted
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgTriplet: 'x64-linux'
        vcpkgArguments: 'boost --featurepackages'

    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake and Ninja - CMakeLists.txt'
      inputs:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: CMakeLists.txt
        useVcpkgToolchainFile: true
        cmakeAppendedArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Release'
