
jobs:
  - job: ubuntu_latest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgTriplet: 'x64-linux'
        vcpkgArguments: 'boost-filesystem'
        # v2025.09.17
        vcpkgGitCommitId: '4334d8b4c8916018600212ab4dd4bbdc343065d1'

    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake and Ninja - CMakeLists.txt'
      inputs:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: CMakeLists.txt
        useVcpkgToolchainFile: true
        cmakeAppendedArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Release'

  - job: macOS_latest
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: Bash@3
      displayName: 'Install gcc'
      inputs:
        targetType: 'inline'
        script: 'brew install gcc'
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgTriplet: 'x64-osx'
        vcpkgArguments: 'boost-filesystem'
        # v2025.09.17
        vcpkgGitCommitId: '4334d8b4c8916018600212ab4dd4bbdc343065d1'
    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake and Ninja - CMakeLists.txt'
      inputs:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: CMakeLists.txt
        useVcpkgToolchainFile: true
        cmakeAppendedArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Release'
        
  - job: windows_latest
    pool:
      name: windows-latest
    steps:
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgTriplet: 'x64-windows'
        vcpkgArguments: 'boost-filesystem'
        # v2025.09.17
        vcpkgGitCommitId: '4334d8b4c8916018600212ab4dd4bbdc343065d1'

    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake and Ninja - CMakeLists.txt'
      inputs:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: CMakeLists.txt
        useVcpkgToolchainFile: true
        cmakeAppendedArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Release'
        
  - job: Windows_VS2019_Hosted
    pool:
      name: windows-2019
    steps:
    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgTriplet: 'x64-windows'
        vcpkgArguments: 'boost-filesystem'

    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake and Ninja - CMakeLists.txt'
      inputs:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: CMakeLists.txt
        useVcpkgToolchainFile: true
        cmakeAppendedArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Release'
